# Generated by Django 3.2.7 on 2021-09-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('slug', models.SlugField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aliexpress_post', to='product.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
