# Generated by Django 3.2.7 on 2021-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211001_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'открытый'), ('closed', 'закрытый'), ('draft', 'чернровик')], default=1, max_length=10, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
